<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groupChatForAttachProtocol.proto

namespace App\Protocol\Proto\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *群聊之加入某个群
 *
 * Generated from protobuf message <code>netsvrBusinessDemo.groupChatForAttachProtocol.GroupChatForAttachProtocol</code>
 */
class GroupChatForAttachProtocol extends \Google\Protobuf\Internal\Message implements \NetsvrBusiness\Contract\RouterDataInterface
{
    use \NetsvrBusiness\Contract\RouterAndDataForProtobufTrait;
    /**
     *群号
     *
     * Generated from protobuf field <code>string groupChatId = 1;</code>
     */
    protected $groupChatId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $groupChatId
     *          群号
     * }
     */
    public function __construct($data = NULL) {
        \App\Protocol\Proto\Protobuf\GPBMetadata\GroupChatForAttachProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     *群号
     *
     * Generated from protobuf field <code>string groupChatId = 1;</code>
     * @return string
     */
    public function getGroupChatId()
    {
        return $this->groupChatId;
    }

    /**
     *群号
     *
     * Generated from protobuf field <code>string groupChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupChatId = $var;

        return $this;
    }

}

