<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadcastProtocol.proto

namespace App\Protocol\Proto\Protobuf\GPBMetadata;

class BroadcastProtocol
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
É
broadcastProtocol.proto$netsvrBusinessDemo.broadcastProtocol"6
BroadcastProtocol
message (	
fromUser (	BHÊApp\\Protocol\\Proto\\Protobufâ\'App\\Protocol\\Proto\\Protobuf\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

