<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groupChatForDetachProtocol.proto

namespace App\Protocol\Proto\Protobuf\GPBMetadata;

class GroupChatForDetachProtocol
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ö
 groupChatForDetachProtocol.proto-netsvrBusinessDemo.groupChatForDetachProtocol"1
GroupChatForDetachProtocol
groupChatId (	BHÊApp\\Protocol\\Proto\\Protobufâ\'App\\Protocol\\Proto\\Protobuf\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

