<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: router.proto

namespace App\Protocol\Proto\Protobuf\GPBMetadata;

class Router
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
 
router.protonetsvrBusinessDemo.router"#
Router
cmd (
data (	BHÊApp\\Protocol\\Proto\\Protobufâ\'App\\Protocol\\Proto\\Protobuf\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

