<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: singleCastProtocol.proto

namespace App\Protocol\Proto\Protobuf\GPBMetadata;

class SingleCastProtocol
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ü
singleCastProtocol.proto%netsvrBusinessDemo.singleCastProtocol"G
SingleCastProtocol
message (	
fromUser (	
toUser (	BHÊApp\\Protocol\\Proto\\Protobufâ\'App\\Protocol\\Proto\\Protobuf\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

